auto: true
# Site settings
title: Dark的异类之路
email: 简书是个好东西@Dark
description: > #
  为了学习html+css+javascript而建立这个博客。
  联系方式：请看右上角bout me 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://darktan.github.io" # the base hostname & protocol for your site
github_username:  Darktan

# Build settings
markdown: rdiscount
